[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi-terraform"

[[constraint]]
  version = "v0.12.0"
  name = "github.com/terraform-providers/terraform-provider-bigip"

# Overrides to match github.com/terraform-providers/terraform-provider-bigip

[[override]]
  revision = "ac2f73035d72e74d6032da5ec7cfcce965db0f65"
  name = "github.com/f5devcentral/go-bigip"
