// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.f5bigip.ltm.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ProfileHttpHttpStrictTransportSecurity {
    /**
     * @return Specifies whether to include the includeSubdomains directive in the HSTS header. The default is enabled. If no string is specified, then default value will be assigned.
     * 
     */
    private @Nullable String includeSubdomains;
    /**
     * @return Specifies the maximum age to assume the connection should remain secure. The default is 16070400 seconds. If no value is specified, then default value will be assigned.
     * 
     */
    private @Nullable Integer maximumAge;
    /**
     * @return Specifies whether to include the HSTS response header. The default is disabled.If no string is specified, then default value will be assigned.
     * 
     */
    private @Nullable String mode;
    /**
     * @return Specifies whether to include the preload directive in the HSTS header. The default is disabled. If no string is specified, then default value will be assigned.
     * 
     */
    private @Nullable String preload;

    private ProfileHttpHttpStrictTransportSecurity() {}
    /**
     * @return Specifies whether to include the includeSubdomains directive in the HSTS header. The default is enabled. If no string is specified, then default value will be assigned.
     * 
     */
    public Optional<String> includeSubdomains() {
        return Optional.ofNullable(this.includeSubdomains);
    }
    /**
     * @return Specifies the maximum age to assume the connection should remain secure. The default is 16070400 seconds. If no value is specified, then default value will be assigned.
     * 
     */
    public Optional<Integer> maximumAge() {
        return Optional.ofNullable(this.maximumAge);
    }
    /**
     * @return Specifies whether to include the HSTS response header. The default is disabled.If no string is specified, then default value will be assigned.
     * 
     */
    public Optional<String> mode() {
        return Optional.ofNullable(this.mode);
    }
    /**
     * @return Specifies whether to include the preload directive in the HSTS header. The default is disabled. If no string is specified, then default value will be assigned.
     * 
     */
    public Optional<String> preload() {
        return Optional.ofNullable(this.preload);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ProfileHttpHttpStrictTransportSecurity defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String includeSubdomains;
        private @Nullable Integer maximumAge;
        private @Nullable String mode;
        private @Nullable String preload;
        public Builder() {}
        public Builder(ProfileHttpHttpStrictTransportSecurity defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.includeSubdomains = defaults.includeSubdomains;
    	      this.maximumAge = defaults.maximumAge;
    	      this.mode = defaults.mode;
    	      this.preload = defaults.preload;
        }

        @CustomType.Setter
        public Builder includeSubdomains(@Nullable String includeSubdomains) {
            this.includeSubdomains = includeSubdomains;
            return this;
        }
        @CustomType.Setter
        public Builder maximumAge(@Nullable Integer maximumAge) {
            this.maximumAge = maximumAge;
            return this;
        }
        @CustomType.Setter
        public Builder mode(@Nullable String mode) {
            this.mode = mode;
            return this;
        }
        @CustomType.Setter
        public Builder preload(@Nullable String preload) {
            this.preload = preload;
            return this;
        }
        public ProfileHttpHttpStrictTransportSecurity build() {
            final var o = new ProfileHttpHttpStrictTransportSecurity();
            o.includeSubdomains = includeSubdomains;
            o.maximumAge = maximumAge;
            o.mode = mode;
            o.preload = preload;
            return o;
        }
    }
}
