// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5BigIP
{
    /// <summary>
    /// ## # f5bigip.GtmServer
    /// 
    /// Manages F5 BIG-IP GTM (Global Traffic Manager) Server resources.
    /// 
    /// A GTM server represents a BIG-IP system, a host, or a server that hosts applications. Servers are identified by their addresses and are organized within datacenters. GTM servers enable GTM to perform load balancing and provide health monitoring for distributed applications.
    /// 
    /// ## Example Usage
    /// 
    /// ### Basic GTM Server (BIG-IP)
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var server1 = new F5BigIP.GtmServer("server1", new()
    ///     {
    ///         Name = "bigip_server1",
    ///         Datacenter = dc1.Name,
    ///         Product = "bigip",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.1.1.1",
    ///             },
    ///         },
    ///         Monitor = "/Common/bigip",
    ///         VirtualServerDiscovery = "true",
    ///         LinkDiscovery = "disabled",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### GTM Server with Multiple Addresses
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var multiAddressServer = new F5BigIP.GtmServer("multi_address_server", new()
    ///     {
    ///         Name = "multi_server",
    ///         Datacenter = dc1.Name,
    ///         Product = "bigip",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.1.1.1",
    ///                 DeviceName = "/Common/bigip1.example.com",
    ///                 Translation = "none",
    ///             },
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.1.1.2",
    ///                 DeviceName = "/Common/bigip2.example.com",
    ///                 Translation = "none",
    ///             },
    ///         },
    ///         Monitor = "/Common/bigip",
    ///         VirtualServerDiscovery = "true",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### GTM Server with Address Translation
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var natServer = new F5BigIP.GtmServer("nat_server", new()
    ///     {
    ///         Name = "nat_server",
    ///         Datacenter = dc1.Name,
    ///         Product = "bigip",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.10.10.10",
    ///                 DeviceName = "/Common/server.example.com",
    ///                 Translation = "192.168.1.10",
    ///             },
    ///         },
    ///         Monitor = "/Common/bigip",
    ///         VirtualServerDiscovery = "true",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Generic Host Server
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var genericHost = new F5BigIP.GtmServer("generic_host", new()
    ///     {
    ///         Name = "generic_server",
    ///         Datacenter = dc1.Name,
    ///         Product = "generic-host",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.20.20.20",
    ///             },
    ///         },
    ///         Monitor = "/Common/tcp",
    ///         VirtualServerDiscovery = "false",
    ///         LinkDiscovery = "disabled",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### Generic Host Server with Virtual Servers
    /// 
    /// For generic-host servers that don't support virtual server discovery, you can manually define virtual servers:
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var genericWithVs = new F5BigIP.GtmServer("generic_with_vs", new()
    ///     {
    ///         Name = "generic_app_server",
    ///         Datacenter = dc1.Name,
    ///         Product = "generic-host",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "192.168.10.100",
    ///             },
    ///         },
    ///         VirtualServerDiscovery = "disabled",
    ///         LinkDiscovery = "disabled",
    ///         VirtualServers = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerVirtualServerArgs
    ///             {
    ///                 Name = "vs_http",
    ///                 Destination = "192.168.10.100:80",
    ///                 Enabled = true,
    ///             },
    ///             new F5BigIP.Inputs.GtmServerVirtualServerArgs
    ///             {
    ///                 Name = "vs_https",
    ///                 Destination = "192.168.10.100:443",
    ///                 Enabled = true,
    ///             },
    ///             new F5BigIP.Inputs.GtmServerVirtualServerArgs
    ///             {
    ///                 Name = "vs_api",
    ///                 Destination = "192.168.10.100:8080",
    ///                 Enabled = true,
    ///                 TranslationAddress = "none",
    ///                 TranslationPort = 0,
    ///             },
    ///         },
    ///         Enabled = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### GTM Server with Prober Settings
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var proberServer = new F5BigIP.GtmServer("prober_server", new()
    ///     {
    ///         Name = "prober_configured_server",
    ///         Datacenter = dc1.Name,
    ///         Product = "bigip",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.30.30.30",
    ///             },
    ///         },
    ///         Monitor = "/Common/bigip",
    ///         VirtualServerDiscovery = "true",
    ///         ProberPreference = "inside-datacenter",
    ///         ProberFallback = "any-available",
    ///         IqAllowPath = true,
    ///         IqAllowServiceCheck = true,
    ///         IqAllowSnmp = true,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ### GTM Server with Resource Limits
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using F5BigIP = Pulumi.F5BigIP;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var dc1 = new F5BigIP.GtmDatacenter("dc1", new()
    ///     {
    ///         Name = "datacenter1",
    ///     });
    /// 
    ///     var limitedServer = new F5BigIP.GtmServer("limited_server", new()
    ///     {
    ///         Name = "resource_limited_server",
    ///         Datacenter = dc1.Name,
    ///         Product = "bigip",
    ///         Addresses = new[]
    ///         {
    ///             new F5BigIP.Inputs.GtmServerAddressArgs
    ///             {
    ///                 Name = "10.40.40.40",
    ///             },
    ///         },
    ///         Monitor = "/Common/bigip",
    ///         VirtualServerDiscovery = "true",
    ///         LimitMaxConnections = 10000,
    ///         LimitMaxBps = 1000000,
    ///         LimitMaxPps = 50000,
    ///         LimitCpuUsage = 80,
    ///         LimitMemAvail = 1024,
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Notes
    /// 
    /// * When creating a GTM server of type `Bigip`, ensure that the BIG-IP device is accessible and properly configured for GTM communication.
    /// 
    /// * Virtual server discovery requires proper iQuery communication between GTM systems.
    /// 
    /// * Address translation is useful when servers are behind NAT.
    /// 
    /// * Multiple addresses can be specified for servers with multiple network interfaces or for redundancy.
    /// 
    /// * Resource limits help prevent a single server from consuming all available capacity in load balancing decisions.
    /// 
    /// * Prober settings control how GTM monitors server health from different network locations.
    /// 
    /// ## Import
    /// 
    /// GTM servers can be imported using the server name or full path:
    /// 
    /// ```sh
    /// $ pulumi import f5bigip:index/gtmServer:GtmServer example /Common/server1
    /// ```
    /// 
    /// or
    /// 
    /// ```sh
    /// $ pulumi import f5bigip:index/gtmServer:GtmServer example server1
    /// ```
    /// </summary>
    [F5BigIPResourceType("f5bigip:index/gtmServer:GtmServer")]
    public partial class GtmServer : global::Pulumi.CustomResource
    {
        /// <summary>
        /// List of IP addresses for the server. Each address block supports:
        /// </summary>
        [Output("addresses")]
        public Output<ImmutableArray<Outputs.GtmServerAddress>> Addresses { get; private set; } = null!;

        /// <summary>
        /// The datacenter where this server resides. Must be a valid datacenter name or full path (e.g., `/Common/datacenter1`).
        /// </summary>
        [Output("datacenter")]
        public Output<string> Datacenter { get; private set; } = null!;

        /// <summary>
        /// Description of the GTM server
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Enable or disable the GTM server
        /// </summary>
        [Output("enabled")]
        public Output<bool?> Enabled { get; private set; } = null!;

        /// <summary>
        /// Allow GTM server to expose route domains. Default is `False`.
        /// </summary>
        [Output("exposeRouteDomains")]
        public Output<bool?> ExposeRouteDomains { get; private set; } = null!;

        /// <summary>
        /// Enable iQuery path probing. Default is `True`.
        /// </summary>
        [Output("iqAllowPath")]
        public Output<bool?> IqAllowPath { get; private set; } = null!;

        /// <summary>
        /// Enable iQuery service checking. Default is `True`.
        /// </summary>
        [Output("iqAllowServiceCheck")]
        public Output<bool?> IqAllowServiceCheck { get; private set; } = null!;

        /// <summary>
        /// Enable iQuery SNMP. Default is `True`.
        /// </summary>
        [Output("iqAllowSnmp")]
        public Output<bool?> IqAllowSnmp { get; private set; } = null!;

        /// <summary>
        /// Maximum CPU usage allowed (percent). 0 means no limit. Default is `0`.
        /// </summary>
        [Output("limitCpuUsage")]
        public Output<int?> LimitCpuUsage { get; private set; } = null!;

        /// <summary>
        /// CPU usage limit status.
        /// </summary>
        [Output("limitCpuUsageStatus")]
        public Output<string> LimitCpuUsageStatus { get; private set; } = null!;

        /// <summary>
        /// Maximum bits per second. 0 means no limit. Default is `0`.
        /// </summary>
        [Output("limitMaxBps")]
        public Output<int?> LimitMaxBps { get; private set; } = null!;

        /// <summary>
        /// Maximum bps limit status.
        /// </summary>
        [Output("limitMaxBpsStatus")]
        public Output<string> LimitMaxBpsStatus { get; private set; } = null!;

        /// <summary>
        /// Maximum concurrent connections. 0 means no limit. Default is `0`.
        /// </summary>
        [Output("limitMaxConnections")]
        public Output<int?> LimitMaxConnections { get; private set; } = null!;

        /// <summary>
        /// Maximum connections limit status.
        /// </summary>
        [Output("limitMaxConnectionsStatus")]
        public Output<string> LimitMaxConnectionsStatus { get; private set; } = null!;

        /// <summary>
        /// Maximum packets per second. 0 means no limit. Default is `0`.
        /// </summary>
        [Output("limitMaxPps")]
        public Output<int?> LimitMaxPps { get; private set; } = null!;

        /// <summary>
        /// Maximum pps limit status.
        /// </summary>
        [Output("limitMaxPpsStatus")]
        public Output<string> LimitMaxPpsStatus { get; private set; } = null!;

        /// <summary>
        /// Available memory limit (MB). 0 means no limit. Default is `0`.
        /// </summary>
        [Output("limitMemAvail")]
        public Output<int?> LimitMemAvail { get; private set; } = null!;

        /// <summary>
        /// Available memory limit status.
        /// </summary>
        [Output("limitMemAvailStatus")]
        public Output<string> LimitMemAvailStatus { get; private set; } = null!;

        /// <summary>
        /// Link discovery mode. Valid values:
        /// </summary>
        [Output("linkDiscovery")]
        public Output<string?> LinkDiscovery { get; private set; } = null!;

        /// <summary>
        /// Monitor assigned to check server health (e.g., `/Common/bigip`, `/Common/tcp`).
        /// </summary>
        [Output("monitor")]
        public Output<string> Monitor { get; private set; } = null!;

        /// <summary>
        /// Name of the GTM server. Must be unique within the partition.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Partition or tenant the server belongs to. Default is `Common`.
        /// </summary>
        [Output("partition")]
        public Output<string?> Partition { get; private set; } = null!;

        /// <summary>
        /// Fallback prober selection. Valid values:
        /// </summary>
        [Output("proberFallback")]
        public Output<string?> ProberFallback { get; private set; } = null!;

        /// <summary>
        /// Prober pool to use when ProberPreference or ProberFallback is set to pool
        /// </summary>
        [Output("proberPool")]
        public Output<string?> ProberPool { get; private set; } = null!;

        /// <summary>
        /// Preferred type of prober. Valid values:
        /// </summary>
        [Output("proberPreference")]
        public Output<string?> ProberPreference { get; private set; } = null!;

        /// <summary>
        /// Type of server. Valid values are:
        /// </summary>
        [Output("product")]
        public Output<string?> Product { get; private set; } = null!;

        /// <summary>
        /// Enable or disable virtual server discovery. Default is `True`. When enabled, GTM automatically discovers virtual servers on BIG-IP systems.
        /// </summary>
        [Output("virtualServerDiscovery")]
        public Output<string?> VirtualServerDiscovery { get; private set; } = null!;

        /// <summary>
        /// List of virtual servers for the GTM server. This is particularly useful for generic-host servers where virtual server discovery is not available. Each VirtualServers block supports:
        /// </summary>
        [Output("virtualServers")]
        public Output<ImmutableArray<Outputs.GtmServerVirtualServer>> VirtualServers { get; private set; } = null!;


        /// <summary>
        /// Create a GtmServer resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public GtmServer(string name, GtmServerArgs args, CustomResourceOptions? options = null)
            : base("f5bigip:index/gtmServer:GtmServer", name, args ?? new GtmServerArgs(), MakeResourceOptions(options, ""))
        {
        }

        private GtmServer(string name, Input<string> id, GtmServerState? state = null, CustomResourceOptions? options = null)
            : base("f5bigip:index/gtmServer:GtmServer", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing GtmServer resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static GtmServer Get(string name, Input<string> id, GtmServerState? state = null, CustomResourceOptions? options = null)
        {
            return new GtmServer(name, id, state, options);
        }
    }

    public sealed class GtmServerArgs : global::Pulumi.ResourceArgs
    {
        [Input("addresses")]
        private InputList<Inputs.GtmServerAddressArgs>? _addresses;

        /// <summary>
        /// List of IP addresses for the server. Each address block supports:
        /// </summary>
        public InputList<Inputs.GtmServerAddressArgs> Addresses
        {
            get => _addresses ?? (_addresses = new InputList<Inputs.GtmServerAddressArgs>());
            set => _addresses = value;
        }

        /// <summary>
        /// The datacenter where this server resides. Must be a valid datacenter name or full path (e.g., `/Common/datacenter1`).
        /// </summary>
        [Input("datacenter", required: true)]
        public Input<string> Datacenter { get; set; } = null!;

        /// <summary>
        /// Description of the GTM server
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Enable or disable the GTM server
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Allow GTM server to expose route domains. Default is `False`.
        /// </summary>
        [Input("exposeRouteDomains")]
        public Input<bool>? ExposeRouteDomains { get; set; }

        /// <summary>
        /// Enable iQuery path probing. Default is `True`.
        /// </summary>
        [Input("iqAllowPath")]
        public Input<bool>? IqAllowPath { get; set; }

        /// <summary>
        /// Enable iQuery service checking. Default is `True`.
        /// </summary>
        [Input("iqAllowServiceCheck")]
        public Input<bool>? IqAllowServiceCheck { get; set; }

        /// <summary>
        /// Enable iQuery SNMP. Default is `True`.
        /// </summary>
        [Input("iqAllowSnmp")]
        public Input<bool>? IqAllowSnmp { get; set; }

        /// <summary>
        /// Maximum CPU usage allowed (percent). 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitCpuUsage")]
        public Input<int>? LimitCpuUsage { get; set; }

        /// <summary>
        /// CPU usage limit status.
        /// </summary>
        [Input("limitCpuUsageStatus")]
        public Input<string>? LimitCpuUsageStatus { get; set; }

        /// <summary>
        /// Maximum bits per second. 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMaxBps")]
        public Input<int>? LimitMaxBps { get; set; }

        /// <summary>
        /// Maximum bps limit status.
        /// </summary>
        [Input("limitMaxBpsStatus")]
        public Input<string>? LimitMaxBpsStatus { get; set; }

        /// <summary>
        /// Maximum concurrent connections. 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMaxConnections")]
        public Input<int>? LimitMaxConnections { get; set; }

        /// <summary>
        /// Maximum connections limit status.
        /// </summary>
        [Input("limitMaxConnectionsStatus")]
        public Input<string>? LimitMaxConnectionsStatus { get; set; }

        /// <summary>
        /// Maximum packets per second. 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMaxPps")]
        public Input<int>? LimitMaxPps { get; set; }

        /// <summary>
        /// Maximum pps limit status.
        /// </summary>
        [Input("limitMaxPpsStatus")]
        public Input<string>? LimitMaxPpsStatus { get; set; }

        /// <summary>
        /// Available memory limit (MB). 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMemAvail")]
        public Input<int>? LimitMemAvail { get; set; }

        /// <summary>
        /// Available memory limit status.
        /// </summary>
        [Input("limitMemAvailStatus")]
        public Input<string>? LimitMemAvailStatus { get; set; }

        /// <summary>
        /// Link discovery mode. Valid values:
        /// </summary>
        [Input("linkDiscovery")]
        public Input<string>? LinkDiscovery { get; set; }

        /// <summary>
        /// Monitor assigned to check server health (e.g., `/Common/bigip`, `/Common/tcp`).
        /// </summary>
        [Input("monitor")]
        public Input<string>? Monitor { get; set; }

        /// <summary>
        /// Name of the GTM server. Must be unique within the partition.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Partition or tenant the server belongs to. Default is `Common`.
        /// </summary>
        [Input("partition")]
        public Input<string>? Partition { get; set; }

        /// <summary>
        /// Fallback prober selection. Valid values:
        /// </summary>
        [Input("proberFallback")]
        public Input<string>? ProberFallback { get; set; }

        /// <summary>
        /// Prober pool to use when ProberPreference or ProberFallback is set to pool
        /// </summary>
        [Input("proberPool")]
        public Input<string>? ProberPool { get; set; }

        /// <summary>
        /// Preferred type of prober. Valid values:
        /// </summary>
        [Input("proberPreference")]
        public Input<string>? ProberPreference { get; set; }

        /// <summary>
        /// Type of server. Valid values are:
        /// </summary>
        [Input("product")]
        public Input<string>? Product { get; set; }

        /// <summary>
        /// Enable or disable virtual server discovery. Default is `True`. When enabled, GTM automatically discovers virtual servers on BIG-IP systems.
        /// </summary>
        [Input("virtualServerDiscovery")]
        public Input<string>? VirtualServerDiscovery { get; set; }

        [Input("virtualServers")]
        private InputList<Inputs.GtmServerVirtualServerArgs>? _virtualServers;

        /// <summary>
        /// List of virtual servers for the GTM server. This is particularly useful for generic-host servers where virtual server discovery is not available. Each VirtualServers block supports:
        /// </summary>
        public InputList<Inputs.GtmServerVirtualServerArgs> VirtualServers
        {
            get => _virtualServers ?? (_virtualServers = new InputList<Inputs.GtmServerVirtualServerArgs>());
            set => _virtualServers = value;
        }

        public GtmServerArgs()
        {
        }
        public static new GtmServerArgs Empty => new GtmServerArgs();
    }

    public sealed class GtmServerState : global::Pulumi.ResourceArgs
    {
        [Input("addresses")]
        private InputList<Inputs.GtmServerAddressGetArgs>? _addresses;

        /// <summary>
        /// List of IP addresses for the server. Each address block supports:
        /// </summary>
        public InputList<Inputs.GtmServerAddressGetArgs> Addresses
        {
            get => _addresses ?? (_addresses = new InputList<Inputs.GtmServerAddressGetArgs>());
            set => _addresses = value;
        }

        /// <summary>
        /// The datacenter where this server resides. Must be a valid datacenter name or full path (e.g., `/Common/datacenter1`).
        /// </summary>
        [Input("datacenter")]
        public Input<string>? Datacenter { get; set; }

        /// <summary>
        /// Description of the GTM server
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Enable or disable the GTM server
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// Allow GTM server to expose route domains. Default is `False`.
        /// </summary>
        [Input("exposeRouteDomains")]
        public Input<bool>? ExposeRouteDomains { get; set; }

        /// <summary>
        /// Enable iQuery path probing. Default is `True`.
        /// </summary>
        [Input("iqAllowPath")]
        public Input<bool>? IqAllowPath { get; set; }

        /// <summary>
        /// Enable iQuery service checking. Default is `True`.
        /// </summary>
        [Input("iqAllowServiceCheck")]
        public Input<bool>? IqAllowServiceCheck { get; set; }

        /// <summary>
        /// Enable iQuery SNMP. Default is `True`.
        /// </summary>
        [Input("iqAllowSnmp")]
        public Input<bool>? IqAllowSnmp { get; set; }

        /// <summary>
        /// Maximum CPU usage allowed (percent). 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitCpuUsage")]
        public Input<int>? LimitCpuUsage { get; set; }

        /// <summary>
        /// CPU usage limit status.
        /// </summary>
        [Input("limitCpuUsageStatus")]
        public Input<string>? LimitCpuUsageStatus { get; set; }

        /// <summary>
        /// Maximum bits per second. 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMaxBps")]
        public Input<int>? LimitMaxBps { get; set; }

        /// <summary>
        /// Maximum bps limit status.
        /// </summary>
        [Input("limitMaxBpsStatus")]
        public Input<string>? LimitMaxBpsStatus { get; set; }

        /// <summary>
        /// Maximum concurrent connections. 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMaxConnections")]
        public Input<int>? LimitMaxConnections { get; set; }

        /// <summary>
        /// Maximum connections limit status.
        /// </summary>
        [Input("limitMaxConnectionsStatus")]
        public Input<string>? LimitMaxConnectionsStatus { get; set; }

        /// <summary>
        /// Maximum packets per second. 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMaxPps")]
        public Input<int>? LimitMaxPps { get; set; }

        /// <summary>
        /// Maximum pps limit status.
        /// </summary>
        [Input("limitMaxPpsStatus")]
        public Input<string>? LimitMaxPpsStatus { get; set; }

        /// <summary>
        /// Available memory limit (MB). 0 means no limit. Default is `0`.
        /// </summary>
        [Input("limitMemAvail")]
        public Input<int>? LimitMemAvail { get; set; }

        /// <summary>
        /// Available memory limit status.
        /// </summary>
        [Input("limitMemAvailStatus")]
        public Input<string>? LimitMemAvailStatus { get; set; }

        /// <summary>
        /// Link discovery mode. Valid values:
        /// </summary>
        [Input("linkDiscovery")]
        public Input<string>? LinkDiscovery { get; set; }

        /// <summary>
        /// Monitor assigned to check server health (e.g., `/Common/bigip`, `/Common/tcp`).
        /// </summary>
        [Input("monitor")]
        public Input<string>? Monitor { get; set; }

        /// <summary>
        /// Name of the GTM server. Must be unique within the partition.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Partition or tenant the server belongs to. Default is `Common`.
        /// </summary>
        [Input("partition")]
        public Input<string>? Partition { get; set; }

        /// <summary>
        /// Fallback prober selection. Valid values:
        /// </summary>
        [Input("proberFallback")]
        public Input<string>? ProberFallback { get; set; }

        /// <summary>
        /// Prober pool to use when ProberPreference or ProberFallback is set to pool
        /// </summary>
        [Input("proberPool")]
        public Input<string>? ProberPool { get; set; }

        /// <summary>
        /// Preferred type of prober. Valid values:
        /// </summary>
        [Input("proberPreference")]
        public Input<string>? ProberPreference { get; set; }

        /// <summary>
        /// Type of server. Valid values are:
        /// </summary>
        [Input("product")]
        public Input<string>? Product { get; set; }

        /// <summary>
        /// Enable or disable virtual server discovery. Default is `True`. When enabled, GTM automatically discovers virtual servers on BIG-IP systems.
        /// </summary>
        [Input("virtualServerDiscovery")]
        public Input<string>? VirtualServerDiscovery { get; set; }

        [Input("virtualServers")]
        private InputList<Inputs.GtmServerVirtualServerGetArgs>? _virtualServers;

        /// <summary>
        /// List of virtual servers for the GTM server. This is particularly useful for generic-host servers where virtual server discovery is not available. Each VirtualServers block supports:
        /// </summary>
        public InputList<Inputs.GtmServerVirtualServerGetArgs> VirtualServers
        {
            get => _virtualServers ?? (_virtualServers = new InputList<Inputs.GtmServerVirtualServerGetArgs>());
            set => _virtualServers = value;
        }

        public GtmServerState()
        {
        }
        public static new GtmServerState Empty => new GtmServerState();
    }
}
