// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.f5bigip;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.f5bigip.FastHttpAppArgs;
import com.pulumi.f5bigip.Utilities;
import com.pulumi.f5bigip.inputs.FastHttpAppState;
import com.pulumi.f5bigip.outputs.FastHttpAppFastCreateMonitor;
import com.pulumi.f5bigip.outputs.FastHttpAppFastCreatePoolMember;
import com.pulumi.f5bigip.outputs.FastHttpAppVirtualServer;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Optional;
import javax.annotation.Nullable;

/**
 * `f5bigip.FastHttpApp` This resource will create and manage FAST HTTP applications on BIG-IP
 * 
 * [FAST documentation](https://clouddocs.f5.com/products/extensions/f5-appsvcs-templates/latest/)
 * 
 * ## Example Usage
 * ```java
 * package generated_program;
 * 
 * import com.pulumi.Context;
 * import com.pulumi.Pulumi;
 * import com.pulumi.core.Output;
 * import com.pulumi.f5bigip.FastHttpApp;
 * import com.pulumi.f5bigip.FastHttpAppArgs;
 * import com.pulumi.f5bigip.inputs.FastHttpAppVirtualServerArgs;
 * import java.util.List;
 * import java.util.ArrayList;
 * import java.util.Map;
 * import java.io.File;
 * import java.nio.file.Files;
 * import java.nio.file.Paths;
 * 
 * public class App {
 *     public static void main(String[] args) {
 *         Pulumi.run(App::stack);
 *     }
 * 
 *     public static void stack(Context ctx) {
 *         var fastHttpApp = new FastHttpApp(&#34;fastHttpApp&#34;, FastHttpAppArgs.builder()        
 *             .application(&#34;fasthttpapp&#34;)
 *             .tenant(&#34;fasthttptenant&#34;)
 *             .virtualServer(FastHttpAppVirtualServerArgs.builder()
 *                 .ip(&#34;10.30.30.44&#34;)
 *                 .port(443)
 *                 .build())
 *             .build());
 * 
 *     }
 * }
 * ```
 * 
 */
@ResourceType(type="f5bigip:index/fastHttpApp:FastHttpApp")
public class FastHttpApp extends com.pulumi.resources.CustomResource {
    /**
     * Name of the FAST HTTPS application.
     * 
     */
    @Export(name="application", type=String.class, parameters={})
    private Output<String> application;

    /**
     * @return Name of the FAST HTTPS application.
     * 
     */
    public Output<String> application() {
        return this.application;
    }
    /**
     * Name of an existing BIG-IP pool.
     * 
     */
    @Export(name="existPoolName", type=String.class, parameters={})
    private Output</* @Nullable */ String> existPoolName;

    /**
     * @return Name of an existing BIG-IP pool.
     * 
     */
    public Output<Optional<String>> existPoolName() {
        return Codegen.optional(this.existPoolName);
    }
    /**
     * Name of an existing BIG-IP HTTPS pool monitor. Monitors are used to determine the health of the application on each server.
     * 
     */
    @Export(name="existingMonitor", type=String.class, parameters={})
    private Output</* @Nullable */ String> existingMonitor;

    /**
     * @return Name of an existing BIG-IP HTTPS pool monitor. Monitors are used to determine the health of the application on each server.
     * 
     */
    public Output<Optional<String>> existingMonitor() {
        return Codegen.optional(this.existingMonitor);
    }
    /**
     * Name of an existing BIG-IP SNAT pool.
     * 
     */
    @Export(name="existingSnatPool", type=String.class, parameters={})
    private Output</* @Nullable */ String> existingSnatPool;

    /**
     * @return Name of an existing BIG-IP SNAT pool.
     * 
     */
    public Output<Optional<String>> existingSnatPool() {
        return Codegen.optional(this.existingSnatPool);
    }
    /**
     * `fast_create_monitor` block takes input for FAST-Generated Pool Monitor.
     * See Pool Monitor below for more details.
     * 
     */
    @Export(name="fastCreateMonitor", type=FastHttpAppFastCreateMonitor.class, parameters={})
    private Output</* @Nullable */ FastHttpAppFastCreateMonitor> fastCreateMonitor;

    /**
     * @return `fast_create_monitor` block takes input for FAST-Generated Pool Monitor.
     * See Pool Monitor below for more details.
     * 
     */
    public Output<Optional<FastHttpAppFastCreateMonitor>> fastCreateMonitor() {
        return Codegen.optional(this.fastCreateMonitor);
    }
    /**
     * `fast_create_pool_members` block takes input for FAST-Generated Pool.
     * See Pool Members below for more details.
     * 
     */
    @Export(name="fastCreatePoolMembers", type=List.class, parameters={FastHttpAppFastCreatePoolMember.class})
    private Output</* @Nullable */ List<FastHttpAppFastCreatePoolMember>> fastCreatePoolMembers;

    /**
     * @return `fast_create_pool_members` block takes input for FAST-Generated Pool.
     * See Pool Members below for more details.
     * 
     */
    public Output<Optional<List<FastHttpAppFastCreatePoolMember>>> fastCreatePoolMembers() {
        return Codegen.optional(this.fastCreatePoolMembers);
    }
    /**
     * List of address to be used for FAST-Generated SNAT Pool.
     * 
     */
    @Export(name="fastCreateSnatPoolAddresses", type=List.class, parameters={String.class})
    private Output</* @Nullable */ List<String>> fastCreateSnatPoolAddresses;

    /**
     * @return List of address to be used for FAST-Generated SNAT Pool.
     * 
     */
    public Output<Optional<List<String>>> fastCreateSnatPoolAddresses() {
        return Codegen.optional(this.fastCreateSnatPoolAddresses);
    }
    /**
     * A `load balancing method` is an algorithm that the BIG-IP system uses to select a pool member for processing a request. F5 recommends the Least Connections load balancing method
     * 
     */
    @Export(name="loadBalancingMode", type=String.class, parameters={})
    private Output</* @Nullable */ String> loadBalancingMode;

    /**
     * @return A `load balancing method` is an algorithm that the BIG-IP system uses to select a pool member for processing a request. F5 recommends the Least Connections load balancing method
     * 
     */
    public Output<Optional<String>> loadBalancingMode() {
        return Codegen.optional(this.loadBalancingMode);
    }
    /**
     * Slow ramp temporarily throttles the number of connections to a new pool member. The recommended value is 300 seconds
     * 
     */
    @Export(name="slowRampTime", type=Integer.class, parameters={})
    private Output</* @Nullable */ Integer> slowRampTime;

    /**
     * @return Slow ramp temporarily throttles the number of connections to a new pool member. The recommended value is 300 seconds
     * 
     */
    public Output<Optional<Integer>> slowRampTime() {
        return Codegen.optional(this.slowRampTime);
    }
    /**
     * Name of the FAST HTTPS application tenant.
     * 
     */
    @Export(name="tenant", type=String.class, parameters={})
    private Output<String> tenant;

    /**
     * @return Name of the FAST HTTPS application tenant.
     * 
     */
    public Output<String> tenant() {
        return this.tenant;
    }
    /**
     * `virtual_server` block will provide `ip` and `port` options to be used for virtual server.
     * See virtual server below for more details.
     * 
     */
    @Export(name="virtualServer", type=FastHttpAppVirtualServer.class, parameters={})
    private Output</* @Nullable */ FastHttpAppVirtualServer> virtualServer;

    /**
     * @return `virtual_server` block will provide `ip` and `port` options to be used for virtual server.
     * See virtual server below for more details.
     * 
     */
    public Output<Optional<FastHttpAppVirtualServer>> virtualServer() {
        return Codegen.optional(this.virtualServer);
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public FastHttpApp(String name) {
        this(name, FastHttpAppArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public FastHttpApp(String name, FastHttpAppArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public FastHttpApp(String name, FastHttpAppArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("f5bigip:index/fastHttpApp:FastHttpApp", name, args == null ? FastHttpAppArgs.Empty : args, makeResourceOptions(options, Codegen.empty()));
    }

    private FastHttpApp(String name, Output<String> id, @Nullable FastHttpAppState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("f5bigip:index/fastHttpApp:FastHttpApp", name, state, makeResourceOptions(options, id));
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static FastHttpApp get(String name, Output<String> id, @Nullable FastHttpAppState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new FastHttpApp(name, id, state, options);
    }
}
