// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.F5BigIP.Sys.Inputs
{

    public sealed class IAppTableRowGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("rows")]
        private InputList<string>? _rows;
        public InputList<string> Rows
        {
            get => _rows ?? (_rows = new InputList<string>());
            set => _rows = value;
        }

        public IAppTableRowGetArgs()
        {
        }
        public static new IAppTableRowGetArgs Empty => new IAppTableRowGetArgs();
    }
}
