// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.f5bigip.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class WafPolicyFileType {
    /**
     * @return Determines whether the file type is allowed or disallowed. In either of these cases the VIOL_FILETYPE violation is issued (if enabled) for an incoming request-
     * * No allowed file type matched the file type of the request.
     * * The file type of the request matched a disallowed file type.
     * 
     */
    private @Nullable Boolean allowed;
    /**
     * @return Specifies the file type name as appearing in the URL extension.
     * 
     */
    private @Nullable String name;
    /**
     * @return Determines the type of the name attribute. Only when setting the type to `wildcard` will the special wildcard characters in the name be interpreted as such
     * 
     */
    private @Nullable String type;

    private WafPolicyFileType() {}
    /**
     * @return Determines whether the file type is allowed or disallowed. In either of these cases the VIOL_FILETYPE violation is issued (if enabled) for an incoming request-
     * * No allowed file type matched the file type of the request.
     * * The file type of the request matched a disallowed file type.
     * 
     */
    public Optional<Boolean> allowed() {
        return Optional.ofNullable(this.allowed);
    }
    /**
     * @return Specifies the file type name as appearing in the URL extension.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }
    /**
     * @return Determines the type of the name attribute. Only when setting the type to `wildcard` will the special wildcard characters in the name be interpreted as such
     * 
     */
    public Optional<String> type() {
        return Optional.ofNullable(this.type);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(WafPolicyFileType defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean allowed;
        private @Nullable String name;
        private @Nullable String type;
        public Builder() {}
        public Builder(WafPolicyFileType defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.allowed = defaults.allowed;
    	      this.name = defaults.name;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder allowed(@Nullable Boolean allowed) {

            this.allowed = allowed;
            return this;
        }
        @CustomType.Setter
        public Builder name(@Nullable String name) {

            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder type(@Nullable String type) {

            this.type = type;
            return this;
        }
        public WafPolicyFileType build() {
            final var _resultValue = new WafPolicyFileType();
            _resultValue.allowed = allowed;
            _resultValue.name = name;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
