// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";
import * as utilities from "../utilities";

export function getVWanConfig(args: GetVWanConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetVWanConfigResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("f5bigip:ssl/getVWanConfig:getVWanConfig", {
        "azureVwanName": args.azureVwanName,
        "azureVwanResourcegroup": args.azureVwanResourcegroup,
        "azureVwanVpnsite": args.azureVwanVpnsite,
    }, opts);
}

/**
 * A collection of arguments for invoking getVWanConfig.
 */
export interface GetVWanConfigArgs {
    readonly azureVwanName: string;
    readonly azureVwanResourcegroup: string;
    readonly azureVwanVpnsite: string;
}

/**
 * A collection of values returned by getVWanConfig.
 */
export interface GetVWanConfigResult {
    readonly azureVwanName: string;
    readonly azureVwanResourcegroup: string;
    readonly azureVwanVpnsite: string;
    readonly bigipGwIp: string;
    readonly hubAddressSpace: string;
    readonly hubConnectedSubnets: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly presharedKey: string;
    readonly vwanGwAddresses: string[];
}
